options:
  check-update: true
  message: true
database:
  source:
    mysql:
      host: localhost
      port: 3306
      user: ItemManager
      password: ItemManagerPassword
      database: minecraft
loader:
  packs-files:
    - ''